# Generated by Django 2.1.4 on 2019-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_created',
            field=models.CharField(max_length=26),
        ),
    ]
