# Generated by Django 2.1.4 on 2019-01-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20190116_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
