# Generated by Django 2.1.4 on 2019-01-16 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_log_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='account',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='narration',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
